# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy Node.js app to Azure Web App - dia-ra-sosnus-develop-frontend

# on:
#   push:
#     branches:
#       - develop

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@master

#     - name: Set up Node.js version
#       uses: actions/setup-node@v1
#       with:
#         node-version: '12.x'

#     - name: npm install, build, and test
#       run: |
#         cd ./ra-front/
#         npm install
#         npm run build --if-present
        
#     - name: PRINT
#       run: |
#         ls .
#         cd ./ra-front/
#         echo "cd ./ra-front/"
#         ls .

#     - name: 'Deploy to Azure Web App'
#       uses: azure/webapps-deploy@v1
#       with:
#         app-name: 'dia-ra-sosnus-develop-frontend'
#         slot-name: 'production'
#         publish-profile: ${{ secrets.AzureAppService_PublishProfile_7207decc2ea34d29821b71960d707a2a }}
#         package: ./ra-front/dist/ra-front/
